### ISSUE TITLE
PyMem_Malloc Allocator

### ISSUE THREAD

**Issue by llllllllll** [QuantStack/xtensor-python#44]
I have run into a few issues with a similar allocator to the one added in #23 and wanted to warn you about them so you can decide to either remove it or fix it.

1. `PyMem_(Malloc|Free)` requires the GIL.
2. As of 3.6, interpreter shutdown causes memory allocated with `PyMem_Malloc` to be freed.

The issue with 1 is that it makes it hard to release the gil because any internal allocations will require the gil and it is not obvious to a consumer what can allocate.

The issue with 2 is that if you store an object at global scope whose destructor invokes `PyMem_Free` you will get a double free or other failure because the memory was already released.

For my application I have just switched to `PyMem_Raw(Malloc|Calloc|Free)` but those are wrappers around malloc|calloc|free with slightly different NULL and 0 handling. I feel bad for adding this without sufficient testing and I hope you haven't had too many issues because of this.

**Comment by JohanMabille** [comment]
Hi,

Thanks for this heads up! No problem for adding this, we were at very early stage and experienced a lot of directions. We have changed our approach and now we wrap the ``PyArray_Object`` instead of a raw pointer that would communicate with python through an allocator, so we don't have this issue anymore.
